site_name: AgencyWiki
site_description: База знаний агентства
docs_dir: docs
site_dir: site

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Тёмная тема
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Светлая тема
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: ru
  - awesome-pages

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - toc:
      permalink: true

extra:
  generator: false
